/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conexionBD;


import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ren Ashbell
 */
public final class FormularioP extends javax.swing.JFrame {
    
     conexion conex = new conexion();
     Connection conet;
     DefaultTableModel modelo;
     Statement st;
     ResultSet rs;
     int idc;
    
    
    

    
    public FormularioP() {
        initComponents();
        setLocationRelativeTo(null);
        consultar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(204, 255, 204));
        panel1.setForeground(new java.awt.Color(102, 153, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre_usuario", "Nombre", "Apellido", "Telefono", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla);

        panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 727, 344));

        jLabel1.setFont(new java.awt.Font("Century", 0, 30)); // NOI18N
        jLabel1.setText("Clientes registrados");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ren Ashbell\\Desktop\\icons\\editar (1).png")); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 150, 40));

        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ren Ashbell\\Desktop\\icons\\eliminar (1).png")); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 150, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ren Ashbell\\Desktop\\icons\\cerrar-sesion (4).png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 30, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

// TODO add your handling code here:
    Eliminaar();
    consultar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        Editar();
        consultar();
       
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
	Logiin login = new Logiin();
	login.setVisible(true);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioP().setVisible(true);
            }
        });
    }
    
    public void consultar () {
        
     String sql = "select * from usuario";
     
        try {
             conet = conex.getConexion(); 
             st = conet.createStatement();
             rs = st. executeQuery(sql);
             Object [] Usuario = new Object [5];
             modelo = (DefaultTableModel) Tabla.getModel();
             
             while (rs.next()) {
             Usuario [0] = rs.getString("Nombre_usuario");
             Usuario [1] = rs.getString("Nombre");
             Usuario [2] = rs.getString("Apellido");
             Usuario [3] = rs.getString("Telefono");
             Usuario [4] = rs.getString("Correo");
             
             modelo.addRow(Usuario);
             
             
             
          }
             Tabla.setModel(modelo);
        } catch (Exception e) {
        }
        
     
        
    }
      public void Editar () {
          
      int fila = Tabla.getSelectedRow();
      
      String Nombre_usuario = Tabla.getValueAt(fila, 0).toString();
      String Nombre = Tabla.getValueAt(fila, 1).toString();
      String Apellido = Tabla.getValueAt(fila, 2).toString();
      String Telefono = Tabla.getValueAt(fila, 3).toString();
      String Correo = Tabla.getValueAt(fila, 4).toString();
      
      
          try {
              PreparedStatement editar = (PreparedStatement) conet.prepareStatement("update usuario set Nombre='"+Nombre+"',Apellido='"+Apellido+"',Telefono='"+Telefono+"',Correo='"+Correo+"' where Nombre_usuario = '"+Nombre_usuario+"'");
              editar.executeUpdate();
              Eliminar();
              //JOptionPane.showMessageDialog(rootPane, "Registro actualizado correctamente!");
              
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, e + "No se pudo actualizar los datos");
          }

       
       
       }
      
      public void Eliminar() {
          
          
          
        for (int i = 1; i <= Tabla.getRowCount(); i++) {
            i -=1 ;
            modelo.removeRow(i);

        
    }
        
         }
      void Eliminaar() {
       int fila = Tabla.getSelectedRow();
          String del = Tabla.getValueAt(fila, 0).toString();

          try {
              PreparedStatement elim = (PreparedStatement) conet.prepareStatement("delete from usuario where Nombre_usuario='"+del+"'");
              elim.executeUpdate();
              Eliminar();

              
          } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "No se pudo eliminar");

        }
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables

}