/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conexionBD;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Ren Ashbell
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtfuera = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtUsuarioo = new javax.swing.JTextField();
        pasConContra = new javax.swing.JPasswordField();
        passContraseña = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        txtfuera.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century", 0, 30)); // NOI18N
        jLabel1.setText("Crear cuenta ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 200, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ren Ashbell\\Desktop\\icons\\registrate (1).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 100, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Telefono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Contraseña");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Correo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Confirmar contraseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("Usuario");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, 30));
        txtNombre.getAccessibleContext().setAccessibleName("Nombre");

        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 140, 30));
        txtApellido.getAccessibleContext().setAccessibleName("Apellido");

        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 140, 30));
        txtTelefono.getAccessibleContext().setAccessibleName("Telefono");

        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 140, 30));
        txtCorreo.getAccessibleContext().setAccessibleName("Correo");

        jPanel1.add(txtUsuarioo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, 30));
        txtUsuarioo.getAccessibleContext().setAccessibleName("Usuario");

        jPanel1.add(pasConContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 140, 30));
        pasConContra.getAccessibleContext().setAccessibleName("Confirmar contraseña");

        jPanel1.add(passContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 140, 30));
        passContraseña.getAccessibleContext().setAccessibleName("Contraseña");

        btnIniciar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ren Ashbell\\Desktop\\icons\\iniciar-sesion (1).png")); // NOI18N
        btnIniciar.setText("Iniciar sesion");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 230, 40));

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conexionBD/icons/agregar (1).png"))); // NOI18N
        btnCrear.setText("Añadir Cuenta");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 230, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel10.setText("Ya tienes una cuenta?");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        
    	  String Nombre_usuario = txtUsuarioo.getText();
          String Nombre = txtNombre.getText();
          String Apellido = txtNombre.getText();
          String Telefono = txtTelefono.getText();
          String Correo = txtCorreo.getText();
          String Contraseña = String.valueOf(passContraseña.getPassword());
          String Confirmar_contraseña = String.valueOf(pasConContra.getPassword());
          txtfuera.setName("txtfuera");
          txtUsuarioo.setName("Usuario");
          txtNombre.setName("Nombre");
          txtApellido.setName("Apellido");
          txtTelefono.setName("Telefono");
          txtCorreo.setName("Correo");
          passContraseña.setName("Contraseña");
          pasConContra.setName("Confirmar contraseña");

          
         
          
          javax.swing.JTextField[] Detectar_null = {txtUsuarioo, txtNombre, txtApellido, txtTelefono, txtCorreo, passContraseña, pasConContra, txtfuera};
          List<String> Det = new ArrayList<>();
          
          
          
         for (javax.swing.JTextField inf : Detectar_null) {
                if (inf.getText().isEmpty() && !"txtfuera".equals(inf.getName())   ) {
                   Det.add(inf.getName());
                }
         }
         
         
         
         if(!Det.isEmpty()) {
             
          JOptionPane.showMessageDialog(null, "Los siguientes campos: " + Det + " estan nulos", "Aviso!", JOptionPane.ERROR_MESSAGE);
          
         }else { 
         
         if (passContraseña.getText().equals(pasConContra.getText())) {
             
             
         Usuario usuarioo = new Usuario();
         usuarioo.setNombre_usuario(Nombre_usuario);
         usuarioo.setNombre(Nombre);
         usuarioo.setApellido(Apellido);
         usuarioo.setTelefono(Telefono);
         usuarioo.setCorreo(Correo);
         usuarioo.setContraseña(Contraseña);
         usuarioo.setConfirmar_contraseña(Confirmar_contraseña);
         
         gesUsuario gesUser = new gesUsuario();
         gesUser.setUsuario(usuarioo);     
         
         
         JOptionPane.showMessageDialog(rootPane, "Cuenta registrada!");
         
         this.dispose();
         Logiin login = new Logiin();
         login.setVisible(true);
             
             
             
         } else { 
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Aviso!", JOptionPane.ERROR_MESSAGE);
                
        }
         
         
      }

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
	Logiin login = new Logiin();
        login.setVisible(true);
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pasConContra;
    private javax.swing.JPasswordField passContraseña;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuarioo;
    private javax.swing.JTextField txtfuera;
    // End of variables declaration//GEN-END:variables
}
